### PR TITLE
Do not register hooks for documents of type :pages

### LINKED ISSUE #93: Having a collection named 'pages' causes error when building site
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      macOS High Sierra      |
| `jekyll`         | 4.0    |
| `github-pages`   | N/A     |

---

## Expected Behaviour

If `pages` is not a valid collection name, then I would expect to see a nice error message saying something like "You cannot use 'pages' as a collection name".

and/or

Documentation that says you can't use 'pages' for a collection name.

## Current Behavior

I created a `pages` collection while on 3.8 and it worked fine. But after upgrading to 4.0, the site wouldn't build.

The problem stems from [this line](https://github.com/jekyll/jekyll/blob/v4.0.0/lib/jekyll/document.rb#L380). It's supposed to be triggering hooks defined for the collection, but because my collection is called 'pages', it ends up triggering hooks defined for pages.

Then, [a hook added by `jekyll-sass-converter`](https://github.com/jekyll/jekyll-sass-converter/blob/v2.0.0/lib/jekyll/converters/scss.rb#L21) tries calling `page.converters`, but in this case, `page` is a `Jekyll::Document`, which does not respond to `:converters`, and you end up with this error...
```
~/.rvm/gems/ruby-2.5.1/gems/jekyll-4.0.0/lib/jekyll/document.rb:403:in `method_missing': undefined method `converters' for #<Jekyll::Document _pages/test_page.md collection=pages> (NoMethodError)
```

## Code Sample

**To reproduce:**
1. create a new Jekyll 4.0 site
2. Add a collection named `pages`..
    ```
    # add this to _config.yml
    collections:
      pages:
        output: true
    ```
3. Create a `_pages` directory and a file `_pages/test_page.rb` that contains...
    ```
    ---
    title: Test Page
    ---
    Hello from test page
    ```
3. Try building the site with `jekyll build --trace`...
    ```
    undefined method `converters' for #<Jekyll::Document _pages/test_page.md collection=pages> (NoMethodError)
    ```

## Why would anyone create a `pages` collection?

I had 3 types of pages I wanted to create: documentation, posts, and general pages. Collections seemed like a way to keep everything better organized.

Before I created the `pages` collection, my content looked something like this...
```
├── 404.html
├── Gemfile
├── Gemfile.lock
├── _config.yml
├── _posts
│   ├── 2019-07-01-things.markdown
│   ├── 2019-07-28-stuff.markdown
│   └── 2019-08-20-neat-stuff.markdown
├── about.markdown
├── collections
│   └── documentation
│       ├── getting_started
│       │   ├── installation.md
│       │   └── prereqs.md
│       └── introduction.md
├── index.markdown
├── other_content
│   ├── foo
│   │   └── ipsum.md
│   └── lorum.md
├── some_content
│   ├── box
│   │   └── jack.md
│   ├── cookies.md
│   └── pizza.md
└── test_page.md
```

After creating a `pages` collection, my content looked more like this..
```
.
├── 404.html
├── Gemfile
├── Gemfile.lock
├── _config.yml
├── index.markdown
└── site_content
    ├── _documentation
    │   ├── getting_started
    │   │   ├── installation.md
    │   │   └── prereqs.md
    │   └── introduction.md
    ├── _pages
    │   ├── about.markdown
    │   ├── other_content
    │   │   ├── foo
    │   │   │   └── ipsum.md
    │   │   └── lorum.md
    │   ├── some_content
    │   │   ├── box
    │   │   │   └── jack.md
    │   │   ├── cookies.md
    │   │   └── pizza.md
    │   └── test_page.md
    └── _posts
        ├── 2019-07-01-things.markdown
        ├── 2019-07-28-stuff.markdown
        └── 2019-08-20-neat-stuff.markdown
```

.... which I find to be much cleaner, especially when you expect lots of different people to  be contributing content.

The solution (for me) is to either simply name the collection something other than `pages`, or stop using collections in this way.

### PR DESCRIPTION
**Pull request by ashmaroli**
`Jekyll::Document` objects in a "pages" collection also have their `type` defined as `:pages`. However, the `scss` and `sass` converters expect to hook into just `Jekyll::Page` objects and subclasses.

Resolves #93

### CODE REVIEW

**Comment by afeld** [comment]
Confirming this worked for me. Thanks!

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix
